version: "3"

services:
  appclient:
    container_name: appclient
    build:
      dockerfile: Dockerfile-dev
      context: ./client
    working_dir: /usr/eunoia/appclient
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./client/:/usr/eunoia/appclient
    depends_on: 
      - appserver
    command: ["npm", "run", "dev"]

  appserver:
    container_name: appserver
    build:
      dockerfile: Dockerfile-dev
      context: ./server
    working_dir: /usr/eunoia/appserver
    environment:
      NODE_ENV: development
      DB_URI: mongodb://appdb:27017/eunoia
      PORT: 4200
      JWT_PRIVATE: 123jwt
    ports:
      - 4200:4200
    volumes:
      - ./server/:/usr/eunoia/appserver
    depends_on: 
      - appdb
    command: ["npm", "run", "dev"]

  appdb:
    container_name: appdb
    image: mongo:4.4.25-focal
    ports:
      - 27017:27017
    volumes:
      - ./:/usr/data/db/eunoia
