version: "3"

services:
  eunoia_client:
    container_name: eunoia_client
    build:
      context: ./client
    working_dir: /var/www/eunoia/client
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - 4000:4000
    volumes:
      - ./client/:/var/www/eunoia/client
    depends_on: 
      - eunoia_server

  eunoia_server:
    container_name: eunoia_server
    environment:
      PORT: 4200
      NODE_ENV: production
    build:
      context: ./server
    ports:
      - 4200:4200
    volumes:
      - ./server/:/var/www/eunoia/server

  nginx_server:
    image: nginx:1.25.3-alpine
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8442:8442